apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: jogodavida-spark-job
spec:
  type: Scala
  mode: cluster
  image: lcsandrade/jogodavida-spark
  imagePullPolicy: Always
  mainClass: JogoDaVidaSpark
  mainApplicationFile: "local:///opt/spark/jars/jogodavida.jar"
  sparkVersion: "3.4.0"
  restartPolicy:
    type: Never
  sparkConf:
    "spark.executor.instances": "2"
    "spark.kubernetes.container.image.pullPolicy": "Always"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.4.0
    serviceAccount: spark
    podName: jogodavida-spark-driver
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 3.4.0
